### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by ghost** [esamattis/geekslides#1]
Followed the install steps and get this error message: 

npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.5
npm info calculating sha1 /usr/local/lib/node/.npm/.cache/geekslides/0.1.0/package.tgz
npm info shasum 66785ee04de85692ae14ab9de5a29f8f7cf1e910
npm info range connect@>= 1.5.2 < 2.0.0
npm info preinstall jade@0.12.4
npm info preinstall express@2.4.2
npm info preinstall socket.io@0.7.7
npm info preinstall geekslides@0.1.0
npm info preinstall connect@1.6.0
npm info preinstall policyfile@0.0.3
npm info preinstall redis@0.6.0
npm info preinstall uglify-js@1.0.3
npm info preinstall socket.io-client@0.7.4
npm ERR! failed to link bins
npm ERR! install failed Error: ENOENT, No such file or directory '/usr/local/bin/geekslides@0.1.0'
npm info install failed rollback
npm info uninstall [ 'geekslides@0.1.0',
npm info uninstall   'jade@0.12.4',
npm info uninstall   'socket.io@0.7.7',
npm info uninstall   'socket.io-client@0.7.4',
npm info uninstall   'policyfile@0.0.3',
npm info uninstall   'redis@0.6.0',
npm info uninstall   'uglify-js@1.0.3',
npm info uninstall   'express@2.4.2',
npm info uninstall   'connect@1.6.0' ]
npm info preuninstall geekslides@0.1.0
npm info preuninstall jade@0.12.4
npm info preuninstall socket.io@0.7.7
npm info preuninstall socket.io-client@0.7.4
npm info preuninstall policyfile@0.0.3
npm info preuninstall redis@0.6.0
npm info preuninstall uglify-js@1.0.3
npm info preuninstall express@2.4.2
npm info preuninstall connect@1.6.0
npm info uninstall socket.io-client@0.7.4
npm info uninstall policyfile@0.0.3
npm info uninstall redis@0.6.0
npm info uninstall uglify-js@1.0.3
npm info uninstall geekslides@0.1.0
npm info uninstall jade@0.12.4
npm info uninstall socket.io@0.7.7
npm info uninstall express@2.4.2
npm info uninstall connect@1.6.0
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info postuninstall socket.io-client@0.7.4
npm info postuninstall policyfile@0.0.3
npm info postuninstall redis@0.6.0
npm info postuninstall uglify-js@1.0.3
npm info postuninstall geekslides@0.1.0
npm info postuninstall jade@0.12.4
npm info postuninstall socket.io@0.7.7
npm info postuninstall express@2.4.2
npm info postuninstall connect@1.6.0
npm info uninstall policyfile@0.0.3 complete
npm info uninstall express@2.4.2 complete
npm info uninstall redis@0.6.0 complete
npm info uninstall geekslides@0.1.0 complete
npm info uninstall jade@0.12.4 complete
npm info uninstall socket.io@0.7.7 complete
npm info uninstall uglify-js@1.0.3 complete
npm info uninstall connect@1.6.0 complete
npm info uninstall socket.io-client@0.7.4 complete
npm info install failed rolled back
npm ERR! Error: ENOENT, No such file or directory '/usr/local/bin/geekslides@0.1.0'
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm ERR! System Darwin 10.6.0
npm ERR! argv { remain: [],
npm ERR! argv   cooked: [ 'install' ],
npm ERR! argv   original: [ 'install' ] }
npm not ok

**Comment by esamattis** [comment]
You have very old version of NPM. Upgrade it to 1.0.x. Also your Node is bit old. Report back if upgrading fixes it.

**Comment by ghost** [comment]
Ah brill, that worked.  Thanks!
